### ISSUE TITLE
scrapi functions

### ISSUE THREAD

**Issue by matthewdodd** [ropensci/musemeta#8]
I'm attempting to gather a lot of information about Greek and Roman art. 

When I type in: met(XXXXXX) the data is returned quickly. Even when grabbing information from multiple different objects the information is returned quickly. 

But when I attempt to use scrapi to grab information, whether I am attempting a random grab [scrapi_random(fields=c('medium','whoList'))], a specific one [scrapi_info(123, fields=c('title','primaryArtistNameOnly','medium'))], or a scrapi search query [scrapi_search(query='rome')] the same error is returned: Error in function (type, msg, asError = TRUE)  : Empty reply from server. 

My ultimate goal is to grab all object six-digit reference numbers that are found when the search query is for 'Greece' or 'Rome,' for further data collection. Any help regarding this would be appreciated.

**Comment by sckott** [comment]
hey @matthewdodd  - thanks for the question.  looking at it now

**Comment by sckott** [comment]
@matthewdodd i think the Scrapi API service is down, I am trying to get them to fix this

**Comment by sckott** [comment]
The api for scrapi is down for now, they said it will be back later. Away from computer, when get back I'll see if I can help

**Comment by matthewdodd** [comment]
It looks like scrapi is back up from my perspective, the functions are now working.

**Comment by sckott** [comment]
@matthewdodd That's great. I'll bring those functions back.

**Comment by sckott** [comment]
@matthewdodd the random endpoint seems to be down still, but the others up, reinstall from github again and those functions should work now
